AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Send mail from api

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
      AllowOrigin: "'*'"

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-Api
      StageName: Prod


  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/form/index.sendMailFormContact
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: Send mail with data from landingPage
      Policies:
        - Statement:
          - Sid: WriteCloudWatchLogs
            Effect: Allow
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
          - Sid: allowSes
            Effect: Allow
            Action:
              - ses:*
            Resource: "*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /contact
            Method: POST
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/api/"
